platzigram/urls.py
# Django
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),

    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# Django
from django.urls import path

from . import views

urlpatterns = [
    path(
        route='',
        view=views.PostFeedView.as_view(),
        name='feed'
    ),

    path(
        route='<int:post_id>',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='new',
        view=views.CreatePostView.as_view(),
        name='new_posts'
    ),
]

users/urls.py
from django.urls import path


from users import views

urlpatterns = [

    path(
        route='login',
        view=views.LoginView.as_view(),
        name='login'),
    path(
        route='logout',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup',
        view=views.SignupView.as_view(),
        name='signup'),
    path(
        route='me/profile',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
    ),

    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

posts/models.py
"""Models for post"""

# Django

from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/images')

    """Metadata"""
    created = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return title and username"""
        return '{} by @{}'.format(self.title, self.user.username)

users/models.py
from django.db import models

"""Creating model for this app"""
from django.contrib.auth.models import User


class Profile(models.Model):
    """Creating profile extends base user"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True, max_length=200)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

posts/views.py
# Posts Views

# Django

from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy


# Models
from .models import Post

# Forms
from .model_form import PostForm


class PostFeedView(LoginRequiredMixin, ListView):
    template_name = 'post/feed.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 3
    context_object_name = 'posts'


class PostDetailView(LoginRequiredMixin, DetailView):
    template_name = 'post/detail.html'
    slug_field = 'id'
    slug_url_kwarg = 'post_id'
    queryset = Post.objects.all()


class CreatePostView(LoginRequiredMixin, CreateView):
    template_name = 'post/create_post.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        return context


# def new_posts(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('posts:feed')
#     else:
#         form = PostForm()
#
#     return render(request, 'post/create_post.html', context={
#         'form': form,
#         'user': request.user,
#         'profile': request.user.profile
#     })

users/views.py
# Django

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth import views as auth_views

from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy

# Models
from posts.models import Post
from users.models import Profile

# Forms
from users.form import SignupForm

# Create your views here.


class UserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'user/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context


class LoginView(auth_views.LoginView):
    template_name = 'user/login.html'
# def login_view(request):
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user:
#             login(request, user)
#             return redirect('posts:feed')
#         else:
#             return render(request, 'user/login.html', {'error': 'Invalid username and password'})
#     return render(request, 'user/login.html')


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    pass
# @login_required
# def logout_view(request):
#     logout(request)
#     return redirect('users:login')


class SignupView(FormView):
    template_name = "user/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


# def signup_view(request):
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             form .save()
#             return redirect('users:login')
#     else:
#         form = SignupForm()
#     return render(request, 'user/signup.html', context={
#         'form': form
#     })


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'user/update_profile.html'
    model = Profile
    fields = ['website', 'phone_number', 'biography', 'picture']

    def get_object(self):
        return self.request.user.profile

    def get_success_url(self):
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})

# @login_required
# def update_profile(request):
#     """Update a user's profile view."""
#     profile = request.user.profile
#
#     if request.method == 'POST':
#         form = ProfileForm(request.POST, request.FILES)
#         if form.is_valid():
#             data = form.cleaned_data
#
#             profile.website = data['website']
#             profile.phone_number = data['phone_number']
#             profile.biography = data['biography']
#             profile.picture = data['picture']
#             profile.save()
#
#             url = reverse('users:update_profile')
#             return redirect(url)
#
#     else:
#         form = ProfileForm()
#
#     return render(
#         request=request,
#         template_name='user/update_profile.html',
#         context={
#             'profile': profile,
#             'user': request.user,
#             'form': form
#         }
#     )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    {% if user.profile.picture %}
                        <a href="{% url 'users:detail' request.user.username %}">
                        <img src="{{ user.profile.picture.url}}" height="35" class="d-inline-block align-top rounded-circle"/>
                        </a>
                    {% else %}
                    <a href="{% url 'users:update_profile' %}">
                        <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                    </a>
                    {% endif %}
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:new_posts' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/post/create_post.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# Title field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/post/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">

            {% include 'post_card.html' %}

        </div>
    </div>
{% endblock %}

templates/post/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">

            {% for post in posts %}
            {% include 'post_card.html' %}
            {% endfor %}
        </div>
    </div>

    {% include 'pagination.html' %}
{% endblock %}

templates/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
                <div class="media pt-3 pl-3 pb-1">
                    <a href="{% url 'users:detail' post.user.username %}">
                    <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                    </a>
                    <div class="media-body">
                        <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
                    </div>
                </div>

                <a href="{% url 'posts:detail' post.id %}">
                <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
                </a>

                <p class="mt-1 ml-2" >
                    <a href="" style="color: #000; font-size: 20px;">
                        <i class="far fa-heart"></i>
                    </a> 30 likes
                </p>
                <p class="ml-2 mt-0 mb-2">
                    <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
                </p>
</div>

templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/user/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update_profile" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url 'posts:detail' post.id %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/user/login.html
{% extends "user/base.html" %}

{% block head_content %}
    <title>Platzigram sing in </title>
{% endblock %}

{% block container %}
    {% if form.errors %}
        <p class="alert alert-danger">Your username and password are incorrects. Please  try again</p>
    {% endif %}
    <form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Username" name="username">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Password" name="password">
    </div>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in!</button>
    <p>Dont have account yet! <a href="{% url 'users:signup' %}">Register here!</a></p>

    </form>
{% endblock %}

templates/user/signup.html
{% extends 'user/base.html' %}

{% block head_content %}
    <title>Sign In!</title>
{% endblock %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

    <div class="form-group">
        <button type="submit"class="btn btn-primary btn-lg btn-block">Register!</button>
    </div>

    </form>
{% endblock %}

templates/user/update_profile.html
{% extends 'base.html' %}
{% load static %}
{% block head_content %}
    <title>@{{ request.user.username }} | Update Profile</title>
{% endblock %}

{% block container %}
<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">
             <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>

                </div>
             {% if form.picture.errors %}
             <div class="alert alert-danger">
                    {% for error in form.picture.errors %}
                        <b>{{ error }}</b>
                    {% endfor %}
             </div>
             {% endif %}

                <hr><br>
             <div class="form-group">
                 <label for="">Website:</label>
                <input
                    type="url"
                    class="form-control {% if form.website.errors %} is-invalid {% endif %}"
                    placeholder="Website"
                    name="website"
                    required="true"
                    value={% if form.website.errors %}{{ form.website.errors }}{% else %} {{ profile.website }}{% endif %}>
                    <div class="invalid-feedback">
                     {% for error in form.website.errors %}
                            {{ error }}
                     {% endfor %}

                     </div>
             </div>

             <div class="form-group">
                 <label for="">Biography:</label>
                 <textarea
                       class="form-control {% if form.biography.errors %} is-invalid {% endif %}"
                       placeholder="Biography"
                       name="biography"
                       >{% if form.biography.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}
                 </textarea>
                    <div class="invalid-feedback">
                         {% for error in form.biography.errors %}
                                {{ error }}
                         {% endfor %}
                     </div>
             </div>

             <div class="form-group">
                 <label for="">Phone number:</label>
                <input
                     type="text"
                     class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}"
                     placeholder="Phone number"
                     name="phone_number"
                     value={% if form.phone_number.errors %}{{ form.phone_number.errors }}{% else %}{{ profile.phone_number }}{% endif %}>

                        <div class="invalid-feedback">
                             {% for error in form.phone_number.errors %}
                                    {{ error }}
                             {% endfor %}
                        </div>
             </div>

             <div class="form-group">
             <button type="submit"class="btn btn-primary btn-lg btn-block mt-5">Update info!</button>
             </div>
             </form>
        </div>
    </div>
 </div>


{% endblock %}